# Site settings
title: Dev Diary
description: Personal thought recording blog
baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://se7endragon.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: se7endragon
user_description: None
user_title: Software Developer
email: se7endragon@naver.com
github_username:  se7endragon


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
